
# Site settings
title: Jianwei Hou
name: Jianwei Hou
subtitle: Ph.D. Candidate
email: houjianwei@ruc.edu.cn
description: >
  how2uuu
baseurl: ""
url: "https://jianweihou.github.io/"
github_username:  jianweihou
disqus_baseurl: "https://jianweihou.github.io/"
permalink: :title
# google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jianwei Hou"




