
# Site settings
title: Jianwei Hou
name: Jianwei Hou
subtitle: Ph.D. Candidate
email: houjianwei@ruc.edu.cn
description: >
  Information Security
baseurl: ""
url: "https://jianweihou.github.io/"
github_username:  jianweihou
disqus_baseurl: "https://jianweihou.github.io/"
# disqus_shortname: https-pesoto-github-io
permalink: :title
# google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jianwei Hou"



# # External gems
# gems:
#   - jekyll-paginate
#   - jemoji
#   - jekyll-seo-tag



# social:
#   - name: GitHub
#     icon: github
#     username: pesoto
#     url: https://github.com/pesoto
#     desc: Fork me on GitHub
#     share: false

#   - name: LinkedIn
#     icon: linkedin
#     username: Paul E. Soto
#     url: https://linkedin.com/pesoto
#     desc: Connect with me on LinkedIn
#     share: true
